apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shorterner
spec:
  selector:
    matchLabels:
      app: url-shorterner
  replicas: 3
  template:
    metadata:
      labels:
        app: url-shorterner
    spec:
      containers:
        - name: url-shorterner
          image: url-shorterner:1.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
          - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /url-shorterner/actuator/health
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /url-shorterner/actuator/health
              port: 8081
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1