apiVersion: v1
kind: Service
metadata:
  name: url-shorterner
spec:
  ports:
    - protocol: "TCP"
      port: 8081        # The port inside the cluster
      targetPort: 8081  # The port exposed by the service
  type: NodePort        # Type of service
  selector:
    app: url-shorterner